# Header
menu:
  Home: /
  Archives: archives
rss: atom.xml

# Content
excerpt_link: Read More

# Sidebar
sidebar: right
widgets:
# - category
- recent_posts
- tag
- archive
- tagcloud

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: G-MZCPTY1J9T
gauges_analytics:
# favicon links are in header.ejs
# favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

root_tag_option:
  root_tag_names:
    - Azure AD
    - AAD Connect
    - AD FS
    - 情報採取
  sub_tag_limit: 20
  sub_tag_sort: 'name' # 未実装

cookieconsent:
  enable: true
  options: {
             "palette": {
               "popup": {
                "background": "#efefef",
                "text": "#404040"
              },
              "button": {
                "background": "#8ec760",
                "text": "#ffffff"
              }
             },
             "theme": "classic",
             "position": "top",
             "static": true,
             "content": {
               "message": "当サイトでは、Googleアナリティクスを使用しており、データの収集のためにCookieを使用しています。\nこのデータは匿名で収集されており、個人を特定するものではありません。\nこの機能はCookieを無効にすることで収集を拒否することが出来ますので、お使いのブラウザの設定をご確認ください。この規約に関しての詳細はGoogleアナリティクスサービス利用規約のページやGoogleポリシーと規約ページをご覧ください。",
               "dismiss": "通知を消去",
               "link": "Cookie recipes",
               "href": "https://policies.google.com/technologies/ads?hl=ja"
             }
           }


# show disclaimer in all article by default. disableDisclaimer of article's option set true hide.
# ex) 
# ---
# title: Article Title
# date: 2020-04-30 10:00
# disableDisclaimer: true
# ---
disclaimer: ※本情報の内容（添付文書、リンク先などを含む）は、作成日時点でのものであり、予告なく変更される場合があります。
